export const INVITE_FAILURE = 'INVITE_FAILURE';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const DELETE_ENTITY_FAILURE = 'DELETE_ENTITY_FAILURE';

export const READ_USER = 'READ_USER';
export const READ_USER_FAILURE = 'READ_USER_FAILURE';
export const READ_USER_SUCCESS = 'READ_USER_SUCCESS';

export const ACTIVATE_USER = 'ACTIVATE_USER';
export const ACTIVATE_USER_FAILURE = 'ACTIVATE_USER_FAILURE';
export const ACTIVATE_USER_SUCCESS = 'ACTIVATE_USER_SUCCESS';

export const READ_ENTITIES = 'READ_ENTITIES';
export const READ_ENTITIES_FAILURE = 'READ_ENTITIES_FAILURE';
export const READ_ENTITIES_SUCCESS = 'READ_ENTITIES_SUCCESS';

export const REGISTER = 'REGISTER';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOG_IN = 'LOG_IN';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';

export const READ_USERS = 'READ_USERS';
export const READ_USERS_FAILURE = 'READ_USERS_FAILURE';
export const READ_USERS_SUCCESS = 'READ_USERS_SUCCESS';

export const REJECT_USER = 'REJECT_USER';
export const REJECT_USER_FAILURE = 'REJECT_USER_FAILURE';
export const REJECT_USER_SUCCESS = 'REJECT_USER_SUCCESS';

export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';

export const LOG_OUT = 'LOG_OUT';

export const READ_NOTIFICATIONS_FAILURE = 'READ_NOTIFICATIONS_FAILURE';

export const GET_OCCUPATION = 'GET_OCCUPATION';
